## Where the samples will be written
save_data: data/run/correction
## Where the vocab(s) will be written
src_vocab: data/run/correction.vocab.src
#tgt_vocab: data/run/correction.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
  train:
    path_src: train/original.src
    path_tgt: train/M3.tgt
    transforms: [filtertoolong]
    weight: 1
  valid:
    path_src: test/original.src
    path_tgt: test/M3.tgt
    transforms: [filtertoolong]

src_seq_length: 110
tgt_seq_length: 110

# silently ignore empty lines in the data
skip_empty_level: silent

save_model: data/run/model
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500

share_vocab: true
share_embeddings: true
word_vec_size: 160
enc_rnn_size: 1000
dec_rnn_size: 1000
